# Generated by Django 5.0.3 on 2024-03-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_cart_singleproductincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_price',
            field=models.FloatField(default=80),
            preserve_default=False,
        ),
    ]
